name: Test_and_publish
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2        
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Start test
        run: |
          pip install -r requirements.txt
          python ./tests/runner.py
          bash <(curl -s https://codecov.io/bash) -f ./tests/cov_report.xml
          echo "Succesful test! Cheers!"

      - name: Start publish package, set up it at first.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
